### ISSUE TITLE
Rapports wpkg

### ISSUE THREAD

**Issue by SambaEdu** [SambaEdu/se3-wpkg#1]
286 rapports à prendre en compte.
Mise à jour de rapports.xml.
Option : -cnewer rapports.xml
TMPrapports.xml:2411: parser error : attributes construct error
7/10/2016" time="13:40:47" mac="00:24:E8:42:CB:9B" ip="172.16.102.48"
typewin=""

```
  ^
```

TMPrapports.xml:2411: parser error : Couldn't find end of Start Tag
rapport line 2411
7/10/2016" time="13:40:47" mac="00:24:E8:42:CB:9B" ip="172.16.102.48"
typewin=""

```
  ^
```

TMPrapports.xml:2412: parser error : Opening and ending tag mismatch:
rapports line 3 and rapport
  </rapport>
            ^
TMPrapports.xml:2413: parser error : Extra content at the end of the
document
  <rapport id="s102-03" datetime="2016-10-19 13:03:09" date="19/10/2016"
time="1
  ^
unable to parse TMPrapports.xml
/var/se3/unattended/install/wpkg
wpkg.admin.xml était à jour.

---

cela venait de la mise à jour des rapports. Il suffit d''un fichier de
rapport erroné (dans mon cas un poste coupé pendant la mise à jour
quelques jours plus tôt) pour que les rapports ne soient plus à jour ....

**Comment by SambaEdu** [comment]
Indications de denis : En ajoutant ce test cela doit suffire : 
tail -4 $rapport | grep -q 'Installed' && ....
A mon avis si le rapport se finit par Installed, il y a toutes les  chances pour qu'il soit ok. En général l'erreur à lieu tout au début  quand le client plante, ou au beau milieu en cas d'erreur active x. Si  la connexion est coupée au milieu du wget,  la probabilité est faible

**Comment by lolo4992** [comment]
La modification crée un bug sur l'affichage des rapports (mauvais rafraichissement de la page). En cours d'investigation.

**Comment by lolo4992** [comment]
La génération de rapports.xml a été entièrement revue pour faire disparaitre les blocages observés. A venir dans la version 0.90 et supérieure.
